name: deploy-to-azure

on: [workflow_dispatch]
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read

env:
  Location: "westeurope"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #client-secret: ${{ secrets.AZURE_CLIENT_SECRET}}
        creds: ${{ secrets.AZURE_CREDENTIALS }}